name: KWeather
version: @version@
main: com.songsofwar.kweather.KWeather
api-version: 1.15
softdepend: [Multiverse-Core, WorldGuard]
commands:
  kweather:
    description: For setting the weather
    usage: /kweather
permissions:
  kweather.admin:
    description: Allows the player to use kweather commands
    default: False